# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshare < Formula
  desc "Quickly share cURLable links to your SSH agent's keys!"
  homepage "https://github.com/willfantom/sshare"
  version "1.1.3"
  license "MIT"

  on_macos do
    url "https://github.com/WillFantom/sshare/releases/download/v1.1.3/sshare_1.1.3_Darwin_all.tar.gz"
    sha256 "a11ba8042fdb149913be260b7bf28d7d0b6e951504dc0f8deffe9c96d4055d11"

    def install
      bin.install "sshare"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/WillFantom/sshare/releases/download/v1.1.3/sshare_1.1.3_Linux_armv6.tar.gz"
      sha256 "ad2e3af15b7f417b851944d1fccbb1825f0df58c659af7b2789f9b05fffb8dd4"

      def install
        bin.install "sshare"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/WillFantom/sshare/releases/download/v1.1.3/sshare_1.1.3_Linux_x86_64.tar.gz"
      sha256 "318ff28c08bc5cf5fa253b7ec8e11665e3ddb0621b74e1a7dfe96c24e7f05be8"

      def install
        bin.install "sshare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillFantom/sshare/releases/download/v1.1.3/sshare_1.1.3_Linux_arm64.tar.gz"
      sha256 "89d8fb9c9371129031ceccd9b49f3d3786eb736e8b899dbc96060cea516f87c4"

      def install
        bin.install "sshare"
      end
    end
  end
end
