# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshare < Formula
  desc "Quickly share cURLable links to your SSH agent's keys!"
  homepage "https://github.com/willfantom/sshare"
  version "0.2.0"
  license "MIT"

  on_macos do
    url "https://github.com/WillFantom/sshare/releases/download/v0.2.0/sshare_0.2.0_Darwin_all.tar.gz"
    sha256 "dbcd162990c6a3c954542a7391bb88c6dd2559a235e19d66bda906b4638ae5cb"

    def install
      bin.install "sshare"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/WillFantom/sshare/releases/download/v0.2.0/sshare_0.2.0_Linux_armv6.tar.gz"
      sha256 "7c262e26efadcd1af60329f6d95f941392db9d1e92f33e9023c2689870ce0fce"

      def install
        bin.install "sshare"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/WillFantom/sshare/releases/download/v0.2.0/sshare_0.2.0_Linux_x86_64.tar.gz"
      sha256 "998b16871948a8533b305676a64c645836526d6cc6fbb78b8004c88b16b8b1b8"

      def install
        bin.install "sshare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillFantom/sshare/releases/download/v0.2.0/sshare_0.2.0_Linux_arm64.tar.gz"
      sha256 "58e307bf008e6a917b085677372b0f5331b5f7be5a673deb5bc97b378da552ff"

      def install
        bin.install "sshare"
      end
    end
  end
end
