# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshare < Formula
  desc "Quickly share cURLable links to your SSH agent's keys!"
  homepage "https://github.com/willfantom/sshare"
  version "0.1.0-beta1"
  license "MIT"

  on_macos do
    url "https://github.com/WillFantom/sshare/releases/download/v0.1.0-beta1/sshare_0.1.0-beta1_Darwin_all.tar.gz"
    sha256 "167e1d95babf16091e4c95f2941ea05fae0361d69f4426349a3568bc97f978c4"

    def install
      bin.install "sshare"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/WillFantom/sshare/releases/download/v0.1.0-beta1/sshare_0.1.0-beta1_Linux_armv6.tar.gz"
      sha256 "615c7a033d4056968706255843faf7c5dd5935daa6f4e974674b9b165007ccef"

      def install
        bin.install "sshare"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/WillFantom/sshare/releases/download/v0.1.0-beta1/sshare_0.1.0-beta1_Linux_x86_64.tar.gz"
      sha256 "a990189c547c54b7f389cad6526b305b46c289e4c6a360f25a9fa6c2071b8dcb"

      def install
        bin.install "sshare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WillFantom/sshare/releases/download/v0.1.0-beta1/sshare_0.1.0-beta1_Linux_arm64.tar.gz"
      sha256 "3d1965701dc03b41954de3b51ae0dca551c208c8b29eb995e53a2f7605eca3d5"

      def install
        bin.install "sshare"
      end
    end
  end
end
